graphqlite:
  namespace:
    # The namespace(s) that will store your GraphQLite controllers.
    # It accept either a string or a list of strings.
    controllers: App\Controller\
    # The namespace(s) that will store your GraphQL types and factories.
    # It accept either a string or a list of strings.
    types:
      - App\Types\
      - App\Entity\
  debug:
    # Include exception messages in output when an error arises.
    INCLUDE_DEBUG_MESSAGE: false
    # Include stacktrace in output when an error arises.
    INCLUDE_TRACE: false
    # Exceptions are not caught by the engine and propagated to Symfony.
    RETHROW_INTERNAL_EXCEPTIONS: false
    # Exceptions that do not implement ClientAware interface are
    # not caught by the engine and propagated to Symfony.
    RETHROW_UNSAFE_EXCEPTIONS: true