# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            string $primo_api_gateway: '%env(string:PRIMO_API_GATEWAY)%'
            string $primo_api_key: '%env(string:PRIMO_APIKEY)%'
            string $primo_catalog_tab: '%env(string:PRIMO_CATALOG_TAB)%'
            string $primo_catalog_scope: '%env(string:PRIMO_CATALOG_SCOPE)%'
            string $primo_articles_tab: '%env(string:PRIMO_ARTICLES_TAB)%'
            string $primo_articles_scope: '%env(string:PRIMO_ARTICLES_SCOPE)%'
            string $primo_vid: '%env(string:PRIMO_VID)%'
            string $primo_inst: '%env(string:PRIMO_INST)%'
            string $elasticsearch_url: '%env(string:ELASTICSEARCH_URL)%'
            string $alma_host: '%env(string:ALMA_HOST)%'
            string $alma_library: '%env(string:ALMA_LIBRARY)%'
            $article_query_config: '@query_config.articles'
            $books_query_config: '@query_config.books'
            $online_query_config: '@query_config.online'
            $video_query_config: '@query_config.video'
            $libkey_apikey: '%env(string:LIBKEY_APIKEY)%'
            $libkey_id: '%env(string:LIBKEY_ID)%'
            $library_id: '%env(string:LIBKEY_ID)%'
            string $crossref_mailto: '%env(string:CROSSREF_MAILTO)%'


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # custom aliases for autowiring
    BCLib\PrimoClient\PrimoClient:
        factory: ['App\ServiceFactory\PrimoClientFactory', 'createCatalogService']

    Elasticsearch\Client:
        factory: ['App\ServiceFactory\ElasticsearchClientFactory', 'createElasticsearchClient']

    BCLib\FulltextFinder\FullTextFinder:
      factory: ['App\ServiceFactory\FullTextFinderFactory', 'createFullTextFinder']

    # QueryConfig for books & more
    query_config.books:
        class: BCLib\PrimoClient\QueryConfig
        autowire: false
        arguments:
            - '%env(string:PRIMO_APIKEY)%'
            - '%env(string:PRIMO_CATALOG_TAB)%'
            - '%env(string:PRIMO_VID)%'
            - '%env(string:PRIMO_CATALOG_SCOPE)%'
            - '%env(string:PRIMO_INST)%'

    # QueryConfig for books & more
    query_config.online:
        class: BCLib\PrimoClient\QueryConfig
        autowire: false
        arguments:
            - '%env(string:PRIMO_APIKEY)%'
            - '%env(string:PRIMO_ONLINE_TAB)%'
            - '%env(string:PRIMO_VID)%'
            - '%env(string:PRIMO_ONLINE_SCOPE)%'
            - '%env(string:PRIMO_INST)%'

    # QueryConfig for video
    query_config.video:
        class: BCLib\PrimoClient\QueryConfig
        autowire: false
        arguments:
            - '%env(string:PRIMO_APIKEY)%'
            - '%env(string:PRIMO_VIDEO_TAB)%'
            - '%env(string:PRIMO_VID)%'
            - '%env(string:PRIMO_VIDEO_SCOPE)%'
            - '%env(string:PRIMO_INST)%'

    # QueryConfig for articles
    query_config.articles:
        class: BCLib\PrimoClient\QueryConfig
        autowire: false
        arguments:
            - '%env(string:PRIMO_APIKEY)%'
            - '%env(string:PRIMO_ARTICLES_TAB)%'
            - '%env(string:PRIMO_VID)%'
            - '%env(string:PRIMO_ARTICLES_SCOPE)%'
            - '%env(string:PRIMO_INST)%'

    GuzzleHttp\Client:
        class: GuzzleHttp\Client
        arguments:
          - { base_uri: '%env(string:PRIMO_API_GATEWAY)%' }

    BCLib\PrimoClient\ApiClient:
        class: BCLib\PrimoClient\ApiClient

    BCLib\LibKeyClient\LibKeyClient:
        class: BCLib\LibKeyClient\LibKeyClient

    # Log client errors to their own channel.
    App\Service\ClientErrorLog\ClientErrorLog:
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: client }